name: default

kind: pipeline
type: docker

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: git.amatashkin.com/github-amatashkin/fl
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    registry: git.amatashkin.com
    username:
      from_secret: docker_local_username
    password:
      from_secret: docker_local_password